---
title: "Species_Distance_graphics"
author: "Thomas Schneider--Bruchon"
date: "20/04/2020"
output: html_document
---


#Environment
```{r}
rm(list=ls())
library(dplyr)
library(scales)
library(reshape)
library(ggplot2)
```


# Variables
```{r}
path = "/Users/Schneider/STAGE_STOC_MNHN/Donnees/"
load(paste(path,"All_species_dataset.Rda", sep ="")) 
data_espece <- read.csv(file = paste(path,"espece.csv",sep=""), encoding="UTF-8")
```


# Only Passerines Conservation
```{r}
passereau <- subset(data_espece,order_tax %in% "Passériformes")
dataset_passereau <- filter(all_species_dataset %>% filter(code_sp %in% passereau$pk_species))
```


# Cleaning
```{r}
rm(data_espece,passereau)
```


# Function
# Get the species occurrence 
```{r}
occurence <- function(datatable,x){
  datatable_oc <- aggregate(datatable$abondance, by = list(code_sp=datatable$code_sp), FUN = length)
  datatable_oc<- datatable_oc[order(datatable_oc$x, decreasing = T),]
  espces_conservees <- datatable_oc[1:x,]
  datatable <- filter(datatable %>% filter(code_sp %in% espces_conservees$code_sp))
  return(datatable)
}
```


# Run 
```{r}
dataset_occ_100_passereau <- occurence(dataset_passereau,100)
dataset_occ_100 <- occurence(all_species_dataset,100)
```


# Observation only EXT polygons
```{r}
dataset_occ_100_passereau_ext <- subset(dataset_occ_100_passereau,INT.EXT %in% 0)
dataset_occ_100_ext <- subset(dataset_occ_100,INT.EXT %in% 0)

# if you want to keep only the observations "far" from the polygon:
#dataset_occ_100_passereau_ext <- filter(dataset_occ_100_passereau_ext,distance > 5 )
```


# Function
# Creation quantile table
```{r}
data_quantile <- function(datatable){
  datatable_q <- aggregate(distance ~ code_sp, datatable, quantile, c(.95,.99))
  datatable_q <- data.frame(datatable_q$code_sp,datatable_q$distance)
  colnames(datatable_q)[1:3] <- c("species","q95","q99")

  quantile_datatable <- melt(datatable_q,id.vars="species")
  colnames(quantile_datatable) <- c("code_sp","quantile","valeur")
  quantile_datatable$quantile <- as.character(as.numeric(gsub("q","",quantile_datatable$quantile))/100)
  return(quantile_datatable)
}

quantile_table_passereau <- data_quantile(dataset_occ_100_passereau_ext)
quantile_table_all <- data_quantile(dataset_occ_100_ext)
```


# Distance Graphics 
```{r}
distance_graph <- function(datatable,quantile_table,save_path){
  
  species <- sort(unique(datatable$code_sp))
  vecI <- sort(unique(seq(1,length(species),20)))
  count = 0
  
  for(i in vecI){
    count = count+1
    
    vecteur_sp <- species[i:min((i+19),length(species))]
    data_sp <- subset(datatable,code_sp %in% vecteur_sp)
    data_sp_ext <- subset(data_sp, INT.EXT %in% 0)
    data_quantile <- subset(quantile_table,code_sp %in% vecteur_sp)
    
    plot <- ggplot(data_sp_ext,aes(x=distance, group = passage, fill = passage))+
    scale_fill_manual(values = c("blue2","red2"))+
    geom_histogram(position="identity", alpha = 0.6)+
    theme(panel.background = element_blank())+
    scale_x_continuous(breaks=pretty_breaks())+
    facet_wrap(~ code_sp, scales = "free", ncol = 4)+
    
    geom_vline(data = subset(data_quantile,quantile==0.95), aes(xintercept = c(valeur)))+
    geom_vline(data = subset(data_quantile,quantile==0.99), aes(xintercept = c(valeur)))+
    
    ggsave(paste(save_path,"Distance_P1P2_Espece_",count,".png", sep=""))
  }
}

distance_graph(dataset_occ_100_passereau_ext,quantile_table_passereau,"")
distance_graph(dataset_occ_100_ext,quantile_table_all,"")
```



# Loading other info needed to build the polygons graphics
```{r}
load(paste("/Users/kevin/OneDrive/Bureau/Thomas/STAGE STOC MNHN/Donnees/BL_all_polygons_F_remanie.Rda", sep = ""))
load(paste("/Users/kevin/OneDrive/Bureau/Thomas/STAGE STOC MNHN/Donnees/espece_BL_STOC.Rda", sep = ""))
monde <- map_data("world")
```


# Polygons Graphics 
```{r}
graph <- function(distance_table,espece_table,polygon_table,save_path){
  
  species <- sort(unique(distance_table$code_sp))
  vecI <- sort(unique(seq(1,length(species),20)))
  count = 0
  
  for(i in vecI){
    count = count+1
    
    vecteur_sp <- species[i:min((i+19),length(species))]
    
    species_table <- subset(espece_BL_STOC, pk_species %in% vecteur_sp) 
    species_area <- subset(BL_all_polygons_F, SCINAME %in% species_table$SCINAME)
    good_sp_area <- species_area %>% filter(SEASONAL %in% c(1,2))
    
    description <- c("1" = "Resident", "2"= "Breeding Season", "3" = "Non-breeding Season", "4" = "Passage")
    cols <- c("1" = "darkmagenta", "2"= "firebrick1","3" = "deepskyblue2", "4" = "gold")
    
    map <- ggplot()+
    geom_polygon(data=monde,aes(x=long,y=lat,group=group),fill="papayawhip",col="black")+
    geom_sf(data = good_sp_area, aes(fill = factor(SEASONAL)), alpha=0.4)+
    scale_fill_manual(values = cols, name = NULL, labels = description)+
    coord_sf(xlim = c(-10,10), ylim = c(40,55))+
    guides(alpha = "none")+
    theme_void()+
    theme(panel.background = element_rect(fill ="slategray1"), plot.title =element_text(color = "#063376", hjust = 0.5, vjust = 3), plot.caption = element_text(face="bold", vjust = 1), legend.margin = margin(0,0,0,1, "cm"))+
    facet_wrap(~ SCINAME, ncol = 4)
    
    ggsave(paste(save_path,"Polygon_Maps_Espece_",count,".png", sep=""))
  }
}

graph(dataset_occ_100_ext,espece_BL_STOC,BL_all_polygons_F,"")
```
